language: kotlin
env:
  global:
    - secure: "BxqgS1ZyQ8CugBmp1zDIbFNLFkX7EHK9OjRKlrndTYQuRR1kd1QNpOGEDGZO+Sp+xUBIm9CQBBzjUkil3E5SsHek32WCdKzhKKUTEbGywngfk
              3zP0i3xINeKwlwyv8iJXijZuBvgSBp/mqvAMyP03/TTBKrdhFehxGaKvZ+EUwAVU01vsCaZqTd97yj6C4OwLiUX9gZpJtxPfNVQYgo+m7tvp4UqPPFTZf6d2
              Lu/lIM+Xa0hiXk6enHlb843WWfjK6BX1uzKH8V68avt3VPQ0f8y9AC44VfK/biGwbFKJSfhglt4YF51nZzM0CxvKTgyxPdy3NG3mCu8jGijirxeIJdWtReGp
              MWcjYgAy5NPtHA5kQ5+0ygMjojRal+kS1xeMeVH/xL89Lzkudj2jA/iLrpFflsBaSs69JY5ZR4WDkHhYNVFZDN/9PjbVf/uGb4BUzNinDEnGm3TeH+8vPCQM
              G4wranxxg6kv/L95Ol4nJcXuSh6i1dFgzk1jDI7dLKhgxuv2Lr87bPhACtxtT3a7YGN2pv6Bvq/ljTX2w51MX1qyv8Ai1yw8jaknQaKGEJ9SSfIQR0rj4DTq
              abvOwXcK/2Q2C+CfOqyhI1E+B6nSRyq2FCskd90t0aVOaX2dRdN6fRC/EY4pwbXrN8rj3MJLYJV/cP658CxGygi6pGEc2c="
    - # ^^ OSSRH_JIRA_USERNAME
    - secure: "o/U9NiG+0Z7UawyC8sajYdYdl+6EUY5x7du2lAwnVdHWfF7jEd1p190FXQnJs/ClOx9G9stIOOlSMSHzUjFalHcamUj0AE1n8PW9H2kmtS8k0
              aHxdRlRpuzH0XRbxHqtMk6qVYiwDfEf4tMRtKjQk/DCFZXfU640QXnt3RqjZEJdJTuozYqbrsvo0xN0EagEAftjm4rUm0qYfYgLUq/+rauaFgLBuJzWvVMc/
              gyG7tt3rQ4libkb/i2ZeGqf2Nmi7lxRLAXSOMV0HX04WMjpik0LckMPMO20EBfmQcaYvsx7dvnKbmesjd8mN9CLMWz85rhFFp3VMPcjWg4JjrHQEssP8AzTL
              OIc+YBKf3pfs++LhVPMWQE3oT4BMjSmrt8mFu2ZwMX64H8lTBadchl8O3okU/6x61BZ8//TlhiYTUw6G1qjFAaaQBhF6NmdVt7Ioo4mgXeOfOgVQnHRhGQhC
              cMHIsxw1ZsEC7rmNJMnPpY/axrf8jWuY5SCeyRIJ3XSlGgK2QlvNpERJfnW58g31vk4yFClbDzW/DYrPvrzz9KIKC7XqOZ+pOjnlPK5SzcecjArot1iJLFIB
              95SsWgUKp80I/hcuu6xehsw+HYBz0cxLmGGjJHf9W8YUAgoSwcSChwMgBhccjl0qMrFeLA+ZIsT1YJMa+UnZ6hHN2BnshU="
    - # ^^ OSSRH_JIRA_PASSWORD
    -   secure: "3o04PslBV77BTg5egersawozeWIrTeBHmB2D/flJXa7TbXL1W/QajPofh3wia2QycbP2egAPo9J6+3ZnuF/w87Mh3Bi6kWCUMB55UR/EXs/7+
                LLLNxKRaiMmxG8+aGZfemKACRaPixR9Xs2uV6CprGjN7DYM4R9cNpvQNi7uKQBH+NA3sSY9MELvEfUCkfj8Sh3YVk7dT++Q/HZjoPausqoKDzf2Gk0EpmwsY
                BEn7wruciEuf0ieeltYWDz0337OMRtQspToswj6V3tR5Plk5F2+k+liWwX0Yu5b4c+aS6vwhnZiHZFFSdHPT2VOio/gSYw7MiQwMQMAhFIVF5sp+fkBx+dJW
                qWiV4QcBWT+Ki2QwdAjMF6gXZePnSqMIakZC7L7Bzt7vaILzuVs7pkXQNF/QpCVQtOa+/lC6czehcDHMZrGIn8GAbYdGnKuNZhnNMQgc02/xytmJeviMVn/7
                QS57LtgxFHUJhn0LowBfmk6y/a631IEWJMWixngqe1MMScAGsD6/Go2svw8yjHkElm2NuL8YAA2gtI4RfyQSq/XBKtBkSdnuLqwsknxIFn7/L/eW3rzfMcFx
                djD0pbGGvnjcIqGvwnPZBlSvxxVkJU+fY7sajsQMzGRe53NlFKwtef1MhDxeUm6WQkmH7GH3AOUSZCNTw8Hk6nwKxkaVSo="
    - # ^^ GPG_KEY_NAME
    -   secure: "xzg8JDs+aU1mt/1JNuX5HlmUtzjQtKRzn4LA943+fbgJKfOdmlWM20YA5Sg+CK33vPSaY+OR4It8607ZcGVue4/E/RV+TCmTwXuJvyZMAnLyz
                r6CoScQB/QC3FYFH+D/GcWvh/5I5NidKA8EL7UREG1O+MFwU8eTW2IFlv+yWf434Z3OSLGP76jhLOdFGtbEU28CZBvpm3K1zFZE3436qmNNAz2efbU/8n4wa
                2yep0SrWaMugwPeUIYsS9xEwPI8w2kz+lsy6tzScfW0soQInCtCw5oTQkKxV40kI3YrrCbKu75OQRVp1cE2YB/tr6TN8oSlFRTqOo1+Bh7pPPuKrIug/U4Ci
                SoApnm9zS5Twjm4MsLr3p54gurOiFc9kOwMowt4EJrF8kC0Fc02UFcm1HuKcNYoBtVj3cIMoULo8bWN7W5u0+uziNgimRXXJjvMGz8qjWJsh3TOK5bDMIIg/
                suRSewS0Ci3fjJ6Q/bGocn5c1SVoSeaEDN5JR+HqpJ903U0GpRuGRX+F6c/xbo6wqIqmtA6F3saFZG/VNoXNxQD7q4MbIsppHBF6BfF6kKOGzRUyciIEWqJJ
                gRlPU9UqGMvKPztje4LaNYLLpgRg1oEh3qSpyiZBeNkCUg8CIafXNOGlBF/Pa118LhtULN71GWE91o9I1ng6R/999PBUFg="
    - # ^^ GPG_PASSPHRASE

before_install:
  - chmod +x deployment/before-deploy.sh
  - chmod +x deployment/deploy.sh
install: mvn install --activate-profiles !build-extras -DskipTests=false -Dmaven.javadoc.skip=true --batch-mode --show-version
script: mvn test --activate-profiles !build-extras --batch-mode

cache:
  directories:
    - ~/.m2/repository

after_success:
  - ./deployment/before-deploy.sh
  - ./deployment/deploy.sh
