# This is a sample build configuration for TravisCI
sudo: required

language: java

services:
- docker

cache:
  directories:
  - .autoconf
  - $HOME/.m2

script:
# -B batch mode makes Maven less verbose
# - mkdir target
# Create a custom settings xml which pulls the FTP Username and Password from the environment variable
- echo "<settings><localRepository>~/.m2/repository</localRepository><servers><server><id>systemkern-snapshots-ftp</id><username>$FTP_USER</username><password>$FTP_PASS</password></server></servers></settings>" > target/settings.xml
- mvn -B -s target/settings.xml clean deploy # -B batch mode makes Maven less verbose
