language: java
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

install: mvn install --settings .maven.xml -DskipTests=false -Dmaven.javadoc.skip=true -Dgpg.skip --batch-mode --show-version

cache:
  directories:
    - ~/.m2/repository

deploy:
  - provider: script
    script: mvn --settings .maven.xml clean deploy -P release
